version: '3'

services:
  web:
    container_name: product-api
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongoservice
    environment:
      MONGO_URI: mongodb://mongoservice:27017/restaurant
    volumes:
      - .:/usr/src/app
  mongoservice:
    container_name: mongo-db-server
    image: mongo
    restart: always
    ports:
      - "27017:27017"